-- ProofU initial schema (docs/data/data-dictionary.md).
--
-- Conventions
--   * Every workspace-owned table carries workspace_id; the query layer enforces isolation.
--   * Identifiers are UUIDv7 generated by the application; gen_random_uuid() is only a fallback.
--   * Enumerations are VARCHAR + CHECK so values can evolve with expand/contract migrations.
--   * Mutable source records carry revision; other mutable rows carry version (optimistic locking).
--   * updated_at is maintained by trigger.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% rows are immutable (%)', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    oidc_subject  varchar(255) NOT NULL,
    oidc_issuer   varchar(512) NOT NULL,
    email         varchar(320) NOT NULL,
    display_name  varchar(120) NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    deleted_at    timestamptz,
    UNIQUE (oidc_issuer, oidc_subject)
);

CREATE TABLE workspaces (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id  uuid NOT NULL REFERENCES users (id),
    name           varchar(120) NOT NULL,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz
);

CREATE TABLE workspace_members (
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    user_id       uuid NOT NULL REFERENCES users (id),
    role          varchar(20) NOT NULL CHECK (role IN ('OWNER')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Career source of truth
-- ---------------------------------------------------------------------------

CREATE TABLE career_entries (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    type          varchar(20) NOT NULL
                  CHECK (type IN ('EMPLOYMENT', 'EDUCATION', 'TRAINING', 'AWARD', 'CERTIFICATION', 'OTHER')),
    title         varchar(200) NOT NULL,
    organization  varchar(200),
    location      varchar(200),
    description   text,
    start_date    date NOT NULL,
    end_date      date,
    visibility    varchar(20) NOT NULL DEFAULT 'PRIVATE'
                  CHECK (visibility IN ('PRIVATE', 'SELECTIVE', 'PUBLIC')),
    status        varchar(20) NOT NULL DEFAULT 'ACTIVE'
                  CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED')),
    revision      bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz,
    CONSTRAINT career_entries_period_check CHECK (end_date IS NULL OR end_date >= start_date)
);
CREATE INDEX career_entries_workspace_updated_idx ON career_entries (workspace_id, updated_at DESC);
CREATE INDEX career_entries_fts_idx ON career_entries
    USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '')));

CREATE TABLE projects (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id     uuid NOT NULL REFERENCES workspaces (id),
    career_entry_id  uuid REFERENCES career_entries (id),
    name             varchar(200) NOT NULL,
    role             varchar(200) NOT NULL,
    summary          text NOT NULL,
    start_date       date,
    end_date         date,
    team_size        integer CHECK (team_size IS NULL OR team_size > 0),
    links            jsonb NOT NULL DEFAULT '[]'::jsonb,
    visibility       varchar(20) NOT NULL DEFAULT 'PRIVATE'
                     CHECK (visibility IN ('PRIVATE', 'SELECTIVE', 'PUBLIC')),
    revision         bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz,
    CONSTRAINT projects_period_check CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);
CREATE INDEX projects_workspace_updated_idx ON projects (workspace_id, updated_at DESC);
CREATE INDEX projects_career_entry_idx ON projects (career_entry_id);

CREATE TABLE achievements (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    project_id    uuid NOT NULL REFERENCES projects (id),
    action        text NOT NULL,
    outcome       text NOT NULL,
    metric_value  numeric(18, 4),
    metric_unit   varchar(40),
    baseline      varchar(200),
    timeframe     varchar(120),
    confidence    numeric(3, 2) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    revision      bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz,
    CONSTRAINT achievements_metric_unit_check CHECK (metric_value IS NULL OR metric_unit IS NOT NULL)
);
CREATE INDEX achievements_project_idx ON achievements (project_id);

CREATE TABLE skills (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    uuid NOT NULL REFERENCES workspaces (id),
    canonical_name  varchar(120) NOT NULL,
    category        varchar(40) NOT NULL,
    aliases         text[] NOT NULL DEFAULT '{}',
    proficiency     varchar(20)
                    CHECK (proficiency IS NULL OR proficiency IN ('NOVICE', 'PRACTITIONER', 'INDEPENDENT', 'ADVANCED', 'STRATEGIC')),
    last_used_at    date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    UNIQUE (workspace_id, canonical_name)
);

CREATE TABLE project_skills (
    project_id  uuid NOT NULL REFERENCES projects (id),
    skill_id    uuid NOT NULL REFERENCES skills (id),
    PRIMARY KEY (project_id, skill_id)
);

CREATE TABLE capabilities (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id           uuid NOT NULL REFERENCES workspaces (id),
    parent_id              uuid REFERENCES capabilities (id),
    name                   varchar(120) NOT NULL,
    definition             text NOT NULL,
    category               varchar(40) NOT NULL
                           CHECK (category IN ('TECHNICAL', 'PROBLEM_SOLVING', 'SYSTEM_DESIGN', 'EXECUTION',
                                               'COLLABORATION', 'LEADERSHIP', 'LEARNING')),
    self_assessed_level    varchar(20)
                           CHECK (self_assessed_level IS NULL OR self_assessed_level IN ('NOVICE', 'PRACTITIONER', 'INDEPENDENT', 'ADVANCED', 'STRATEGIC')),
    evidence_based_level   varchar(20)
                           CHECK (evidence_based_level IS NULL OR evidence_based_level IN ('NOVICE', 'PRACTITIONER', 'INDEPENDENT', 'ADVANCED', 'STRATEGIC')),
    evidence_criteria      text,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    deleted_at             timestamptz
);
CREATE INDEX capabilities_workspace_idx ON capabilities (workspace_id);

-- ---------------------------------------------------------------------------
-- Claims and evidence
-- ---------------------------------------------------------------------------

CREATE TABLE claims (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    text          text NOT NULL,
    claim_type    varchar(20) NOT NULL CHECK (claim_type IN ('FACT', 'INFERENCE', 'OPINION')),
    sensitivity   varchar(20) NOT NULL DEFAULT 'INTERNAL'
                  CHECK (sensitivity IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')),
    revision      bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz
);
CREATE INDEX claims_workspace_updated_idx ON claims (workspace_id, updated_at DESC);

CREATE TABLE evidence (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    type          varchar(20) NOT NULL
                  CHECK (type IN ('FILE', 'URL', 'REPOSITORY', 'COMMIT', 'METRIC', 'CERTIFICATE', 'NOTE', 'REFERENCE_LETTER')),
    title         varchar(200) NOT NULL,
    source        varchar(20) NOT NULL CHECK (source IN ('USER_INPUT', 'EXTERNAL_IMPORT', 'SYSTEM_EXTRACTED')),
    uri           text,
    object_key    varchar(512),
    mime_type     varchar(120),
    size_bytes    bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
    sha256        char(64),
    verification  varchar(20) NOT NULL DEFAULT 'UNVERIFIED'
                  CHECK (verification IN ('UNVERIFIED', 'USER_VERIFIED', 'EXTERNALLY_VERIFIED', 'EXPIRED')),
    sensitivity   varchar(20) NOT NULL DEFAULT 'INTERNAL'
                  CHECK (sensitivity IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')),
    confidence    numeric(3, 2) NOT NULL DEFAULT 0 CHECK (confidence >= 0 AND confidence <= 1),
    captured_at   timestamptz NOT NULL,
    revision      bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz,
    CONSTRAINT evidence_location_check CHECK (uri IS NOT NULL OR object_key IS NOT NULL)
);
CREATE INDEX evidence_workspace_updated_idx ON evidence (workspace_id, updated_at DESC);
CREATE INDEX evidence_workspace_verification_idx ON evidence (workspace_id, verification);

CREATE TABLE claim_evidence (
    claim_id     uuid NOT NULL REFERENCES claims (id),
    evidence_id  uuid NOT NULL REFERENCES evidence (id),
    relation     varchar(20) NOT NULL CHECK (relation IN ('SUPPORTS', 'REFUTES', 'PARTIALLY_SUPPORTS')),
    scope        text,
    confidence   numeric(3, 2) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    created_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (claim_id, evidence_id, relation),
    CONSTRAINT claim_evidence_scope_check CHECK (relation <> 'PARTIALLY_SUPPORTS' OR scope IS NOT NULL)
);
CREATE INDEX claim_evidence_evidence_idx ON claim_evidence (evidence_id);

CREATE TABLE capability_evidence (
    capability_id  uuid NOT NULL REFERENCES capabilities (id),
    evidence_id    uuid NOT NULL REFERENCES evidence (id),
    PRIMARY KEY (capability_id, evidence_id)
);

-- Claims may cite career records; the revision is pinned for reproducibility.
CREATE TABLE claim_sources (
    claim_id         uuid NOT NULL REFERENCES claims (id),
    source_type      varchar(20) NOT NULL CHECK (source_type IN ('CAREER_ENTRY', 'PROJECT', 'ACHIEVEMENT')),
    source_id        uuid NOT NULL,
    source_revision  bigint NOT NULL CHECK (source_revision >= 1),
    PRIMARY KEY (claim_id, source_type, source_id)
);

-- ---------------------------------------------------------------------------
-- Job postings
-- ---------------------------------------------------------------------------

CREATE TABLE job_postings (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id         uuid NOT NULL REFERENCES workspaces (id),
    external_posting_id  varchar(200),
    canonical_url        text,
    company              varchar(200) NOT NULL,
    role_title           varchar(200) NOT NULL,
    published_at         timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    deleted_at           timestamptz
);
CREATE UNIQUE INDEX job_postings_external_idx ON job_postings (workspace_id, external_posting_id)
    WHERE external_posting_id IS NOT NULL;
CREATE INDEX job_postings_workspace_updated_idx ON job_postings (workspace_id, updated_at DESC);

CREATE TABLE job_posting_snapshots (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    posting_id    uuid NOT NULL REFERENCES job_postings (id),
    source        varchar(20) NOT NULL CHECK (source IN ('MANUAL_TEXT', 'URL_FETCH', 'CAREER_OPS')),
    source_url    text,
    raw_text      text NOT NULL,
    content_hash  char(64) NOT NULL,
    captured_at   timestamptz NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (posting_id, content_hash)
);
CREATE INDEX job_posting_snapshots_fts_idx ON job_posting_snapshots
    USING gin (to_tsvector('simple', raw_text));
CREATE TRIGGER job_posting_snapshots_immutable
    BEFORE UPDATE OR DELETE ON job_posting_snapshots
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE TABLE requirements (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    snapshot_id  uuid NOT NULL REFERENCES job_posting_snapshots (id),
    category     varchar(20) NOT NULL
                 CHECK (category IN ('REQUIRED', 'PREFERRED', 'RESPONSIBILITY', 'SKILL', 'BEHAVIORAL')),
    text         text NOT NULL,
    span_start   integer,
    span_end     integer,
    confidence   numeric(3, 2) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    status       varchar(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED')),
    approved_at  timestamptz,
    sort_order   integer NOT NULL DEFAULT 0,
    version      bigint NOT NULL DEFAULT 1,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT requirements_span_check CHECK ((span_start IS NULL AND span_end IS NULL)
                                              OR (span_start >= 0 AND span_end > span_start)),
    CONSTRAINT requirements_approved_check CHECK ((status = 'APPROVED') = (approved_at IS NOT NULL))
);
CREATE INDEX requirements_snapshot_idx ON requirements (snapshot_id, sort_order);

-- ---------------------------------------------------------------------------
-- Applications
-- ---------------------------------------------------------------------------

CREATE TABLE applications (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    snapshot_id   uuid NOT NULL REFERENCES job_posting_snapshots (id),
    company       varchar(200) NOT NULL,
    role_title    varchar(200) NOT NULL,
    status        varchar(30) NOT NULL DEFAULT 'INTERESTED'
                  CHECK (status IN ('INTERESTED', 'PREPARING', 'SUBMITTED', 'DOCUMENT_PASSED', 'DOCUMENT_REJECTED',
                                    'NO_RESPONSE', 'WITHDRAWN', 'HANDOFF_READY', 'HANDED_OFF_TO_ITERVIEW',
                                    'REVIEW_PENDING', 'REVIEWED')),
    deadline_at   timestamptz,
    version       bigint NOT NULL DEFAULT 1,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz
);
CREATE INDEX applications_workspace_updated_idx ON applications (workspace_id, updated_at DESC);
CREATE INDEX applications_workspace_active_idx ON applications (workspace_id, status)
    WHERE status NOT IN ('WITHDRAWN', 'REVIEWED', 'HANDED_OFF_TO_ITERVIEW');

CREATE TABLE application_status_events (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id  uuid NOT NULL REFERENCES applications (id),
    from_status     varchar(30),
    to_status       varchar(30) NOT NULL,
    note            text,
    occurred_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX application_status_events_application_idx ON application_status_events (application_id, occurred_at);
CREATE TRIGGER application_status_events_append_only
    BEFORE UPDATE OR DELETE ON application_status_events
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- ---------------------------------------------------------------------------
-- Documents and lineage
-- ---------------------------------------------------------------------------

CREATE TABLE documents (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    uuid NOT NULL REFERENCES workspaces (id),
    application_id  uuid REFERENCES applications (id),
    type            varchar(20) NOT NULL CHECK (type IN ('RESUME', 'COVER_LETTER', 'PORTFOLIO')),
    title           varchar(200) NOT NULL,
    language        varchar(10) NOT NULL DEFAULT 'ko',
    version         bigint NOT NULL DEFAULT 1,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);
CREATE INDEX documents_workspace_updated_idx ON documents (workspace_id, updated_at DESC);
CREATE INDEX documents_application_idx ON documents (application_id);

CREATE TABLE document_versions (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id        uuid NOT NULL REFERENCES documents (id),
    parent_id          uuid REFERENCES document_versions (id),
    label              varchar(120),
    content_json       jsonb NOT NULL,
    template_version   varchar(40) NOT NULL,
    prompt_version     varchar(40),
    model_ref          varchar(120),
    created_by         varchar(10) NOT NULL CHECK (created_by IN ('USER', 'AI')),
    created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX document_versions_document_idx ON document_versions (document_id, created_at DESC);

CREATE TABLE provenance_links (
    version_id       uuid NOT NULL REFERENCES document_versions (id),
    block_id         varchar(120) NOT NULL,
    source_type      varchar(20) NOT NULL
                     CHECK (source_type IN ('CAREER_ENTRY', 'PROJECT', 'ACHIEVEMENT', 'CLAIM', 'EVIDENCE', 'REQUIREMENT')),
    source_id        uuid NOT NULL,
    source_revision  bigint NOT NULL CHECK (source_revision >= 1),
    relation         varchar(20) NOT NULL CHECK (relation IN ('DERIVED_FROM', 'CITES', 'ADDRESSES')),
    PRIMARY KEY (version_id, block_id, source_type, source_id, relation)
);
CREATE TRIGGER provenance_links_immutable
    BEFORE UPDATE ON provenance_links
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE TABLE submission_snapshots (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id       uuid NOT NULL REFERENCES applications (id),
    document_version_id  uuid NOT NULL REFERENCES document_versions (id),
    posting_snapshot_id  uuid NOT NULL REFERENCES job_posting_snapshots (id),
    hash                 char(64) NOT NULL,
    submitted_at         timestamptz NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX submission_snapshots_application_idx ON submission_snapshots (application_id, submitted_at DESC);
-- ADR-0006: never updated or deleted in place. Account deletion runs a dedicated purge.
CREATE TRIGGER submission_snapshots_immutable
    BEFORE UPDATE OR DELETE ON submission_snapshots
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE TABLE reviews (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id      uuid NOT NULL REFERENCES applications (id),
    observed_fact       text NOT NULL,
    hypothesis          text NOT NULL,
    rationale           text,
    confidence          varchar(10) NOT NULL DEFAULT 'LOW' CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH')),
    improvement_action  text,
    verification_plan   text,
    version             bigint NOT NULL DEFAULT 1,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reviews_application_idx ON reviews (application_id);

CREATE TABLE interview_handoffs (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id   uuid NOT NULL REFERENCES applications (id),
    idempotency_key  varchar(120) NOT NULL,
    handoff_id       varchar(120),
    status           varchar(20) NOT NULL DEFAULT 'REQUESTED'
                     CHECK (status IN ('REQUESTED', 'SENT', 'FAILED', 'CANCELLED')),
    consent_at       timestamptz NOT NULL,
    payload          jsonb NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (application_id, idempotency_key)
);

-- ---------------------------------------------------------------------------
-- Asynchronous work and exports
-- ---------------------------------------------------------------------------

-- ADR-0004: PostgreSQL-backed queue polled with SKIP LOCKED until a broker is justified.
CREATE TABLE jobs (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id),
    type          varchar(40) NOT NULL,
    status        varchar(20) NOT NULL DEFAULT 'QUEUED'
                  CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    payload       jsonb NOT NULL,
    result        jsonb,
    error_code    varchar(60),
    attempts      integer NOT NULL DEFAULT 0,
    max_attempts  integer NOT NULL DEFAULT 3,
    scheduled_at  timestamptz NOT NULL DEFAULT now(),
    started_at    timestamptz,
    finished_at   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jobs_queue_idx ON jobs (scheduled_at) WHERE status = 'QUEUED';
CREATE INDEX jobs_workspace_idx ON jobs (workspace_id, created_at DESC);

CREATE TABLE exports (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id         uuid NOT NULL REFERENCES workspaces (id),
    document_version_id  uuid NOT NULL REFERENCES document_versions (id),
    format               varchar(10) NOT NULL CHECK (format IN ('DOCX', 'PDF', 'MARKDOWN', 'JSON')),
    template_version     varchar(40) NOT NULL,
    renderer_version     varchar(40),
    status               varchar(20) NOT NULL DEFAULT 'REQUESTED'
                         CHECK (status IN ('REQUESTED', 'RENDERING', 'VALIDATING', 'READY', 'FAILED', 'EXPIRED')),
    error_code           varchar(60),
    object_key           varchar(512),
    sha256               char(64),
    size_bytes           bigint,
    page_count           integer,
    mime_type            varchar(120),
    expires_at           timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX exports_version_idx ON exports (document_version_id, format, status);

CREATE TABLE ai_executions (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    uuid NOT NULL REFERENCES workspaces (id),
    job_id          uuid REFERENCES jobs (id),
    purpose         varchar(40) NOT NULL,
    provider        varchar(40) NOT NULL,
    model           varchar(120) NOT NULL,
    prompt_version  varchar(40) NOT NULL,
    policy_version  varchar(40) NOT NULL,
    input_hash      char(64) NOT NULL,
    status          varchar(20) NOT NULL CHECK (status IN ('SUCCEEDED', 'FAILED', 'REJECTED_BY_VALIDATION')),
    input_tokens    integer,
    output_tokens   integer,
    cost_micros     bigint,
    latency_ms      integer,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ai_executions_workspace_idx ON ai_executions (workspace_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Audit
-- ---------------------------------------------------------------------------

CREATE TABLE audit_events (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid,
    actor_id      uuid,
    actor_type    varchar(20) NOT NULL CHECK (actor_type IN ('USER', 'SYSTEM', 'OPERATOR')),
    action        varchar(60) NOT NULL,
    target_type   varchar(40) NOT NULL,
    target_id     uuid,
    before_hash   char(64),
    after_hash    char(64),
    request_id    varchar(64),
    occurred_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_events_workspace_idx ON audit_events (workspace_id, occurred_at DESC);
CREATE TRIGGER audit_events_append_only
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'users', 'workspaces', 'career_entries', 'projects', 'achievements', 'skills', 'capabilities',
        'claims', 'evidence', 'job_postings', 'requirements', 'applications', 'documents', 'reviews',
        'interview_handoffs', 'jobs', 'exports'
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            t || '_set_updated_at', t
        );
    END LOOP;
END $$;
